# This is a basic workflow to help you get started with Actions

name: AIO Docker Builder

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # Runs at 03:00 UTC on the 7, 14, 21 and 28th of every month
    - cron: '0 3 7,14,21,28 1-12 ?'
  push:
    paths:
    - 'Dockerfile'
    - 'android-env-vars.sh'
    - 'Makefile'
    - '.github/workflows/builder.yml'
    branches:
    - 'master'

env:
  DOCKER_USERNAME: fr3akyphantom
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform: ['bionic', 'focal']

    steps:

    - uses: actions/checkout@v2

    - name: Bypass Build
      if: contains(github.event.head_commit.message, '[skip ci]')
      run: echo -e "Dummy Step for bypassing the main build" && exit 0

    - name: Prepare Docker Environment
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Create & Push the Bionic Droid Builder Container
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: make ${{ matrix.platform }}_worker

    - name: Pull & Run/Test the Bionic Droid Builder Container
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: make test NAME=${{ matrix.platform }}

  metadata:
    runs-on: ubuntu-latest
    needs: [build]

    steps:

    - name: Refresh MicroBadger Metadata for Container Infos
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      run: curl -X POST "https://hooks.microbadger.com/images/fr3akyphantom/droid-builder/BvX646w7iSxCNiWg_M7-amdz4qo="

